
//Set up data


let homeTopBook = 3

let bookData = [
    Book(bookname:"book 01", title:"Heroic Male Beginners ¾ View",  cover: "b01isocover", banner: "b03banner", tutorial: book1Tutorials ),
    Book(bookname: "book 02", title: "Heroic Male Intermediate ¾ View",  cover: "b02isocover", banner: "b03banner", tutorial: book2Tutorials),
    Book(bookname: "book 03", title: "Heroic Male Advanced ¾ View",  cover: "b03isocover",banner: "b01banner", tutorial: book3Tutorials),
    Book(bookname:"book 04", title:"Arm Muscles",  cover: "b04isocover",banner: "b03banner", tutorial: book4Tutorials),
    Book(bookname: "book 05", title: "Dynamic Kicking",  cover: "b05isocover",banner: "b03banner", tutorial: book5Tutorials),
    Book(bookname: "book 06", title: "Heroic Male Beginners Front View",  cover: "b06isocover",banner: "b01banner", tutorial: book6Tutorials),
    Book(bookname:"book 07", title:"Heroic Male Intermediate Front View",  cover: "b07isocover",banner: "b03banner", tutorial: book7Tutorials),
    Book(bookname:"book 08", title:"Face Front View",  cover: "b07isocover",banner: "b03banner", tutorial: book7Tutorials)]


let book0Tutorials = [
    Tutorial(book:"book00", t:"t01", image:"b01t01p29", text: "Full Figure",level: "Level 1",length: 13 )]

let book1Tutorials = [
    Tutorial(book:"book01", t:"t01", image:"b01t01p29", text: "Full Figure",level: "Level 1",length: 29 ),
    Tutorial(book:"book01", t:"t02",image:"b01t02p28", text: "Basic Head",level: "Level 1",length: 28),
    Tutorial(book:"book01", t:"t03",image:"b01t03p18", text: "Basic Hand",level: "Level 1",length: 18)]

let book2Tutorials = [
    Tutorial(book:"book02", t:"t01",image:"mi3_4figure21", text: "Full Figure",level: "Level 2",length: 21 ),
    Tutorial(book:"book02", t:"t02",image:"mi3_4head19", text: "The Head",level: "Level 2",length: 19),
    Tutorial(book:"book02", t:"t03",image:"mi3_4torso18", text: "The Torso",level: "Level 2",length: 18 ),
    Tutorial(book:"book02", t:"t04",image:"mi3_4arm11", text: "The Arms",level: "Level 2",length: 11),
    Tutorial(book:"book02", t:"t05",image:"mi3_4leg10", text: "The Legs",level: "Level 2",length: 10 ),
    Tutorial(book:"book02", t:"t06",image:"mi3_4hand11", text: "The Hands",level: "Level 2",length: 11),
    Tutorial(book:"book02", t:"t07",image:"mi3_4foot08", text: "The Feet",level: "Level 2",length: 08)]

let book3Tutorials = [
    Tutorial(book:"book03", t:"t01",image:"ma3_4figure13", text: "Full figure",level: "Level 3",length: 13 ),
    Tutorial(book:"book03", t:"t02",image:"ma3_4torso13", text: "The Head",level: "Level 3",length: 13 ),
    Tutorial(book:"book03", t:"t03",image:"ma3_4legs12", text: "The Torso",level: "Level 3",length: 12 ),
    Tutorial(book:"book03", t:"t04",image:"ma3_4head17", text: "The Arms",level: "Level 3",length: 17 ),
    Tutorial(book:"book03", t:"t05",image:"ma3_4hands07", text: "The Legs",level: "Level 3",length: 7 ),
    Tutorial(book:"book03", t:"t06",image:"ma3_4foot07", text: "The Hands",level: "Level 3",length: 7 ),
    Tutorial(book:"book03", t:"t07",image:"ma3_4arms12", text: "The Feet",level: "Level 3",length: 7 )
]

let book4Tutorials = [
    Tutorial(book:"book04", t:"t01",image:"maflexa21", text: "Arm flex 1",level: "Level 3",length: 21 ),
    Tutorial(book:"book04", t:"t02",image:"maflexb16", text: "Arm flex 2",level: "Level 3",length: 16 ),
    Tutorial(book:"book04", t:"t03",image:"maflexc16", text: "Arm flex 3",level: "Level 3",length: 16 ),
    Tutorial(book:"book04", t:"t04",image:"maflexd18", text: "Arm flex 4",level: "Level 3",length: 18 ),
    Tutorial(book:"book04", t:"t05",image:"maflexe12", text: "Arm flex 5",level: "Level 3",length: 12 ),
    Tutorial(book:"book04", t:"t06",image:"maflexf18", text: "Arm flex 6",level: "Level 3",length: 18 ),
    Tutorial(book:"book04", t:"t07",image:"maflexg16", text: "Arm flex 7",level: "Level 3",length: 16 )
]

let book5Tutorials = [
    Tutorial(book:"book05", t:"t01",image:"midynamickicka0117", text: "Dynamic Kick 1",level: "Level 2",length: 17 ),
    Tutorial(book:"book05", t:"t02",image:"midynamickicka0217", text: "Dynamic Kick 2",level: "Level 2",length: 17 ),
    Tutorial(book:"book05", t:"t03",image:"midynamickicka0317", text: "Dynamic Kick 3",level: "Level 2",length: 17 ),
    Tutorial(book:"book05", t:"t04",image:"midynamickicka0417", text: "Dynamic Kick 4",level: "Level 2",length: 17 ),
    Tutorial(book:"book05", t:"t05",image:"midynamickicka0516", text: "Dynamic Kick 5",level: "Level 2",length: 16 ),
    Tutorial(book:"book05", t:"t06",image:"midynamickicka0617", text: "Dynamic Kick 6",level: "Level 2",length: 17 ),
    Tutorial(book:"book05", t:"t07",image:"midynamickicka0717", text: "Dynamic Kick 1",level: "Level 2",length: 17 ),
    Tutorial(book:"book05", t:"t08",image:"midynamickicka0817", text: "Dynamic Kick 1",level: "Level 2",length: 17 )
]

let book6Tutorials = [
    Tutorial(book:"book06", t:"t01",image:"b06t01p28", text: "Full Figure",level: "Level 1",length: 28 ),
    Tutorial(book:"book06", t:"t02",image:"b06t02p14", text: "Basic Head",level: "Level 1",length: 14  ),
    Tutorial(book:"book06", t:"t03",image:"b06t03p16", text: "Basic Hand",level: "Level 1",length: 16 )
]

let book7Tutorials = [
    Tutorial(book:"book07", t:"t01",image:"b07t01p19", text: "Full Figure",level: "Level 2",length: 19 ),
    Tutorial(book:"book07", t:"t02",image:"b07t02p22", text: "The Face",level: "Level 2",length: 22 ),
    Tutorial(book:"book07", t:"t03",image:"b07t03p18", text: "The Torso",level: "Level 2",length: 18 ),
    Tutorial(book:"book07", t:"t04",image:"b07t04p10", text: "The Arm",level: "Level 2",length: 10 ),
    Tutorial(book:"book07", t:"t05",image:"b07t05p09", text: "The Leg",level: "Level 2",length: 09 ),
    Tutorial(book:"book07", t:"t06",image:"b07t06p11", text: "The Hand",level: "Level 2",length: 11 ),
    Tutorial(book:"book07", t:"t07",image:"b07t07p07", text: "The Foot",level: "Level 2",length: 07 )
]

let tutorialData = [
    Tutorial(book:"book01", t:"t01", image:"b01t01p29", text: "Full Figure",level: "Level 1",length: 29 ),
    Tutorial(book:"book01", t:"t02",image:"b01t02p28", text: "Basic Head",level: "Level 1",length: 28),
    Tutorial(book:"book01", t:"t03",image:"b01t03p18", text: "Basic Hand",level: "Level 1",length: 18),
    Tutorial(book:"book02", t:"t01",image:"mi3_4figure21", text: "Full Figure",level: "Level 2",length: 21 ),
    Tutorial(book:"book02", t:"t02",image:"mi3_4head19", text: "The Head",level: "Level 2",length: 19),
    Tutorial(book:"book02", t:"t03",image:"mi3_4torso18", text: "The Torso",level: "Level 2",length: 18 ),
    Tutorial(book:"book02", t:"t04",image:"mi3_4arm11", text: "The Arms",level: "Level 2",length: 11),
    Tutorial(book:"book02", t:"t05",image:"mi3_4leg10", text: "The Legs",level: "Level 2",length: 10 ),
    Tutorial(book:"book02", t:"t06",image:"mi3_4hand11", text: "The Hands",level: "Level 2",length: 11),
    Tutorial(book:"book02", t:"t07",image:"mi3_4foot08", text: "The Feet",level: "Level 2",length: 08),
    Tutorial(book:"book03", t:"t01",image:"ma3_4figure13", text: "Full figure",level: "Level 3",length: 13 ),
    Tutorial(book:"book03", t:"t02",image:"ma3_4torso13", text: "The Head",level: "Level 3",length: 13 ),
    Tutorial(book:"book03", t:"t03",image:"ma3_4legs12", text: "The Torso",level: "Level 3",length: 12 ),
    Tutorial(book:"book03", t:"t04",image:"ma3_4head17", text: "The Arms",level: "Level 3",length: 17 ),
    Tutorial(book:"book03", t:"t05",image:"ma3_4hands07", text: "The Legs",level: "Level 3",length: 7 ),
    Tutorial(book:"book03", t:"t06",image:"ma3_4foot07", text: "The Hands",level: "Level 3",length: 7 ),
    Tutorial(book:"book03", t:"t07",image:"ma3_4arms12", text: "The Feet",level: "Level 3",length: 12 ),
    Tutorial(book:"book04", t:"t01",image:"maflexa21", text: "Arm flex 1",level: "Level 3",length: 21 ),
    Tutorial(book:"book04", t:"t02",image:"maflexb16", text: "Arm flex 2",level: "Level 3",length: 16 ),
    Tutorial(book:"book04", t:"t03",image:"maflexc16", text: "Arm flex 3",level: "Level 3",length: 16 ),
    Tutorial(book:"book04", t:"t04",image:"maflexd18", text: "Arm flex 4",level: "Level 3",length: 18 ),
    Tutorial(book:"book04", t:"t05",image:"maflexe12", text: "Arm flex 5",level: "Level 3",length: 12 ),
    Tutorial(book:"book04", t:"t06",image:"maflexf18", text: "Arm flex 6",level: "Level 3",length: 18 ),
    Tutorial(book:"book04", t:"t07",image:"maflexg16", text: "Arm flex 7",level: "Level 3",length: 16 ),
    Tutorial(book:"book05", t:"t01",image:"midynamickicka0117", text: "Dynamic Kick 1",level: "Level 2",length: 17 ),
    Tutorial(book:"book05", t:"t02",image:"midynamickicka0217", text: "Dynamic Kick 2",level: "Level 2",length: 17 ),
    Tutorial(book:"book05", t:"t03",image:"midynamickicka0317", text: "Dynamic Kick 3",level: "Level 2",length: 17 ),
    Tutorial(book:"book05", t:"t04",image:"midynamickicka0417", text: "Dynamic Kick 4",level: "Level 2",length: 17 ),
    Tutorial(book:"book05", t:"t05",image:"midynamickicka0516", text: "Dynamic Kick 5",level: "Level 2",length: 16 ),
    Tutorial(book:"book05", t:"t06",image:"midynamickicka0617", text: "Dynamic Kick 6",level: "Level 2",length: 17 ),
    Tutorial(book:"book05", t:"t07",image:"midynamickicka0717", text: "Dynamic Kick 1",level: "Level 2",length: 17 ),
    Tutorial(book:"book05", t:"t08",image:"midynamickicka0817", text: "Dynamic Kick 1",level: "Level 2",length: 17 ),
    Tutorial(book:"book06", t:"t01",image:"b06t01p28", text: "Full Figure",level: "Level 1",length: 28 ),
    Tutorial(book:"book06", t:"t02",image:"b06t02p14", text: "Basic Head",level: "Level 1",length: 14  ),
    Tutorial(book:"book06", t:"t03",image:"b06t03p16", text: "Basic Hand",level: "Level 1",length: 16 ),
    Tutorial(book:"book07", t:"t01",image:"b07t01p19", text: "Full Figure",level: "Level 2",length: 19 ),
    Tutorial(book:"book07", t:"t02",image:"b07t02p22", text: "The Face",level: "Level 2",length: 22 ),
    Tutorial(book:"book07", t:"t03",image:"b07t03p18", text: "The Torso",level: "Level 2",length: 18 ),
    Tutorial(book:"book07", t:"t04",image:"b07t04p10", text: "The Arm",level: "Level 2",length: 10 ),
    Tutorial(book:"book07", t:"t05",image:"b07t05p09", text: "The Leg",level: "Level 2",length: 09 ),
    Tutorial(book:"book07", t:"t06",image:"b07t06p11", text: "The Hand",level: "Level 2",length: 11 ),
    Tutorial(book:"book07", t:"t07",image:"b07t07p07", text: "The Foot",level: "Level 2",length: 07 )
]

var helpTextD: [String: String] =
    



["b00t01p01": "Welcome to Draw.\nAn app designed to help artists of all levels improve their drawing skills. ",
"b00t01p02": "The more you draw, the better you get. It’s not a talent, it’s a skill and we are here to help you learn.",
"b00t01p03": "How it works. \nEach book will contain several tutorials focusing on different areas of illustration.",
"b00t01p04": "The pages of each book will follow every part of the drawing, with the key points described in detail.",
"b00t01p05": "The books are broken up into several levels.",
"b00t01p06": "Level 1 is the easiest. \nThese books will focus on the basic forms needed to draw anything. They are great for beginners but also good those a bit more practiced to help brush up on the basics ",
"b00t01p07": "Level 2 looks at the forms in more detail.  \nThese books are great for the composition of anatomy and will help you draw at a high level with good anatomy and dynamic posing.",
"b00t01p08": "Level 3 \nThese books examine what is beneath the outer layer of our drawing. It analyses the muscles of anatomy first, then looks at the planes these features create.",
"b00t01p09": "Our artist Will Sliney uses different colour pencils throughout the tutorials, but you can use any tools you like.",
"b00t01p10": "The blue lines should indicate light pencil that you will erase ",
"b00t01p11": "The red lines indicate the muscular structure.",
"b00t01p12": "The purple lines are the sculptural planes. ",
"b00t01p13": "Start by laying down the basic shape of the head",
"b01t01p01": "The black lines are the final artwork, those lines that will not be erased. ",
"b01t01p02": "Using the size of the head, we can lay out markers for proportions",
"b01t01p03": "Your hero is 8 heads high",
"b01t01p04": "Lay out the figure as simply as this. With circles as the joints and lines to indicate the limbs and torso",
"b01t01p05": "Note the shoulders should be half a head down",
"b01t01p06": "The Hands reach down at the bottom of the 4th head alongside the hips",
"b01t01p07": "The legs reach down to 8 heads down. With these indicators, we can lay more solid down forms on top",
"b01t01p08": "Two three dimensional shapes, the Top and bottom forms are cylinders, and the middle one is a sphere",
"b01t01p09": "Draw in the larger top cylinder to represent the chest",
"b01t01p10": "A sphere for the stomach, which can help us visualise how the torso can bend and rotate if we were twisting the body",
"b01t01p11": "And the small cylinder for the waist",
"b01t01p12": "These spheres will represent the ball and socket joints that our arms and legs rotate from. Namely the shoulder and the hips",
"b01t01p13": "Some more three dimensional shapes we will use for the arms and the legs",
"b01t01p14": "Start off the arms and legs with a long cylinder that reaches the ball we drew to mark the elbow",
"b01t01p15": "Then use a tapered cylinder for the lower half of each limb",
"b01t01p16": "The hands are covered in more detail in their own tutorial. Draw in the shapes for the legs, and connect the forms together",
"b01t01p17": "Finally, draw in a cylinder to represent the neck",
"b01t01p18": "Using the head tutorial, draw in where the facial features will go",
"b01t01p19": "The chest line will go from the point where your arm meets the Shoulder, down to the line that is two heads down",
"b01t01p20": "I like to connect the major cylinders together",
"b01t01p21": "Great. That’s the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final figure over it.",
"b01t01p22": "Use the head tutorial and draw in what is often the most important part of your figure",
"b01t01p23": "Draw in the neck and whatever neckline you want depending on what clothes your figure is wearing",
"b01t01p24": "Now outline the shoulder and arms. Note the trapezius muscle will make the line from his shoulder go up around his neck",
"b01t01p25": "Most tops will go down the belt line, which is at the top of your cylinder",
"b01t01p26": "Then outline those chest muscles",
"b01t01p27": "Use a lot of straight lines to draw in the legs. Most important is to outline the difference in shapes between the thighs and the calves",
"b01t01p28": "Keep the foot nice and simple",
"b01t01p29": "And there you have it.  You can fully erase the basic forms now to show off your character",
"b01t02p01": "Lets start with an oval shape to represent the head",
"b01t02p02": "Draw two lines across to split it up into thirds",
"b01t02p03": "Our drawing will be looking at the head at an angle. This line will be the centre line of our face",
"b01t02p04": "Let’s take a look at this form represented by a 3D shape. This should help you visualise how the centre line rotates around the form as we look at it from a different angle",
"b01t02p05": "Now, to help us lay out where the features go, let us add some more lines. Take the middle and bottom segment, and draw a line 1/3rd down in each segment",
"b01t02p06": "We now know where to put the facial features. Let us add in ovals for the eyes along this line",
"b01t02p07": "Draw a line from the centre of the eyes straight down the head. This will tell us exactly where to draw the mouth",
"b01t02p08": "The top line is where we draw the eyebrows. You can draw the basics shapes of a rectangle joined to a triangle",
"b01t02p09": "Where the centre line meets our third line, is where to put the nose. Remember, check the facial features book that outlines how to draw the nose",
"b01t02p10": "The the mouth goes on the bottom line, and its width goes from the two centre lines drawn from our eyes",
"b01t02p11": "We know where to put the ear thanks to the lines from our nose and eyes",
"b01t02p12": "Let’s sharpen up the jaw line. Bring it to meet the chin, which is directly under the mouth, using the same lines from the eye",
"b01t02p13": "Continue the jawline and chin line around to the other side of the face",
"b01t02p14": "Add in the hair line",
"b01t02p15": "And extent the back of the head. Our skull goes out slightly further than the initial oval shape we draw",
"b01t02p16": "Great. That’s the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final figure over it",
"b01t02p17": "Remember, the facial features are important, and we have a whole book dedicated to them.  Use it to learn how to draw them from each angle",
"b01t02p18": "Everybody's features are different. Feel free to experiment with different facial shapes and sizes.",
"b01t02p19": "Use the forms we laid out as guides where to draw in the detailed versions of each feature",
"b01t02p20": "We look at the ear in the Features book too",
"b01t02p21": "Now draw in the crown of the head, or use the outline to draw whatever hairstyle you like",
"b01t02p22": "Draw in the jaw line, ignoring the curve of the initial oval",
"b01t02p23": "Add in a few features. A line from the chin up towards the ear can indicate a strong jawline",
"b01t02p24": "I like to indicate the bottom lip with a small line which helps tell us that the lip protrudes from the face. ",
"b01t02p25": "A small curve can show the “ala” area around the nostril",
"b01t02p26": "And a curve here can help define the planes of the face.",
"b01t02p27": "And there you have it.  You can fully erase the basic forms now",
"b01t02p28": "Take a look at Level 2 of this figure to take your drawing up to the next stage. Or why not share your drawing with us.",
"b01t03p01": "Drawing the hands at an angle can be difficult. So always take a look at your own hands for reference. Draw in two rectangles as the palms of your hand ",
"b01t03p02": " Break the finger joints down into rectangles that extend from the top of your palm of your hand",
"b01t03p03": " The tops of these rectangles curve down to indicate middle finger being the longest and the pinky being the smallest",
"b01t03p04": "Your fingers have three joints and there for three bendable areas.  ",
"b01t03p05": "Extending from the palm, I like to draw a cylinder, almost representing the first bone of your thumb as a ball joint ",
"b01t03p06": "The second bone of the thumb extends from this like the fingers ",
"b01t03p07": "And the third follows. ",
"b01t03p08": "Break the rectangles used to outline the fingers into their own parts",
"b01t03p09": "On the right hand here, the pinky is obscured by the ring finger",
"b01t03p10": "Great. That’s the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final hand over it",
"b01t03p11": "Each finger joins your sectioned off rectangles together.",
"b01t03p12": "Remember, the middle finger is the longest",
"b01t03p13": "The ring finger is slightly longer than the index finger",
"b01t03p14": "The pinky is the smallest",
"b01t03p15": "Lets draw the thumb, but note, we only indicate a small part of the ball joint, as the flesh surrounding it blends into the hand",
"b01t03p16": "Same for the left hand. Draw the top two bones as normal, then a small bit of the ball joint as it blends into the hand.",
"b01t03p17": "We can outline the hands going into the palms using the rectangle we drew in stage one",
"b01t03p18": "Where the finger lines end, draw a small curve to indicate the knuckles where they should be seen",
"b01t03p19": "And there you have it.  You can fully erase the basic forms now",
"b01t03p20": "Take a look at Level 2 of the hand to take your drawing up to the next stage. Or why not share your drawing with us",
"b02t01p01": "Start by laying down the basic shape of the head.",
"b02t01p02": "Using the size of the head, we can lay out markers for proportions. .Our figure is 8 heads high.",
"b02t01p03": "Lay out the figure as simply as this. With circles as the joints and lines to indicate the limbs and torso. Use the level 1 tutorial if you need help here.",
"b02t01p04": "Now we can draw in the basic forms starting with the chest.",
"b02t01p05": "Remember, each section is individually covered in more detail in this book.",
"b02t01p06": "Always reference the grid of 8 heads to know where to line up the features. The belly button should be 3 heads down.",
"b02t01p07": "The hips should be around 4 heads down. ",
"b02t01p08": "At this stage, the legs and the arms can be treated similarly.",
"b02t01p09": "Use the tutorials for the hand and the foot when you are drawing them in.",
"b02t01p10": "The bottom half of the leg and hand get thinner as they reach towards the wrist and foot.",
"b02t01p11": "Outline the hands and the feet. Reference their individual tutorials. ",
"b02t01p12": "Lastly connect the head to the neck.",
"b02t01p13": "That is the basic proportions mapped out. Lightly erase the lines and let us take the definition of the forms to the next level.",
"b02t01p14": "Here is where the individual tutorials really come into play. Make sure you look at them.",
"b02t01p15": "Continue refining the forms.",
"b02t01p16": "Look at how the body parts interconnect. The chest muscle connects strongly to the shoulder, which the arm muscle emerges from.",
"b02t01p17": "Similarly, the legs emerge from the hips.",
"b02t01p18": "Draw in the feet.",
"b02t01p19": "And the hands, referring the their tutorials.",
"b02t01p20": "Great. That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final figure over it",
"b02t01p21": "Take a look at Level 3 of the full figure to fully understand how the muscles and plains work. Or why not share your drawing with us. ",
"b02t02p01": "Start with a simple spherical shape for the head.",
"b02t02p02": "Take a look at this form represented by a 3D shape. This should help you visualise how the centre line rotates around the form as we look at it from a different angle,",
"b02t02p03": "Draw in a horizontal and vertical line through the sphere. With the vertical one at an angle in the direction that the head will look towards.",
"b02t02p04": "The head is not fully round, in fact it is important to create the planes of the face that are the side of the head and the front of the face. ",
"b02t02p05": "We can create those planes by taking a vertical slice off the sphere. ",
"b02t02p06": " From these three points we can draw in the bottom half of the face. ",
"b02t02p07": "Take the point where the jaw line meets the chopped sphere as a halfway marker from the spheres midline, in order to find out how far down the chin should go. ",
"b02t02p08": "Now we can clearly see the planes of the face.  ",
"b02t02p09": "Lightly erase some lines to give us a better view. ",
"b02t02p10": "Now draw a line horizontally half ways down our skull shape. This will be the eye line. Divide the front plane in half too.",
"b02t02p11": " Draw some more horizontal lines down. One that is 1/3rd down from the eyes to the jaw. The other just slightly lower, marked by the bottom of our original sphere.",
"b02t02p12": "Now, like in the level 1 tutorial, we can mark in where the facial features go.",
"b02t02p13": "Remember, the facial features are covered in depth in their own book.",
"b02t02p14": "The ear should go from the bottom of the nose, up to the eyebrows.",
"b02t02p15": "Draw in your characters hairline, which can help define the planes of the face.",
"b02t02p16": "Great. That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final head over it.",
"b02t02p17": "I like to start with the eyes as they are often the first feature we look at. ",
"b02t02p18": "Add in the nose.",
"b02t02p19": "The eyebrows.",
"b02t02p20": "The mouth.",
"b02t02p21": "And the ears.",
"b02t02p22": "We can use our layout lines to draw the shape of the face. Depending on the face you are drawing, you can add in a slight protrusion for the cheek bones.",
"b02t02p23": "Follow the lines around and mark in the hairline to complete the basic head shape.",
"b02t02p24": "And there you have it.  You can fully erase the basic forms now.",
"b02t02p25": "Take a look at Level 3 of the head to fully understand how the muscles and plains work. Or why not share your drawing with us.",
"b02t03p01": "Start by laying out the lines that will represent the shoulders, and hips.",
"b02t03p02": "The chest should stretch from shoulder to shoulder.",
"b02t03p03": "The rib cage and the back is a large form that takes up most of the volume of the torso.",
"b02t03p04": "The bottom half of the torso is shaped like a cylinder, down to the waist.",
"b02t03p05": "The shoulders connect into the chest. They rise up higher following there the collarbone will go",
"b02t03p06": "The neck then emerges from the chest, it will connected to the face by a group of muscles.",
"b02t03p07": "The area that will be the abs comes down from the ribcage. It goes right down passed the waist towards the groin area.",
"b02t03p08": "That is the basic proportions mapped out. Lightly erase the lines and so we can bring the definition of the forms to the next level.",
"b02t03p09": "The pecs are two separate large muscles.",
"b02t03p10": "Define the collarbone as it goes from the top of the chest over the shoulder.",
"b02t03p11": "The shoulders will connect to the arms through the deltoid.",
"b02t03p12": "Draw in the ribcage at the front and then the lats which wrap around from under the shoulder to the back.",
"b02t03p13": "Now the abs. Note how one the belly button is in a gap between four abs.",
"b02t03p14": "The oblique muscles emerge from the side of the abs at an angle up towards the lats.",
"b02t03p15": "Draw in four small muscles which will connect the lats to the obliques.",
"b02t03p16": "Then define the hips.",
"b02t03p17": "Finally, the neck muscles. The most important two at the front, connect from the ears, down to the middle point of the collarbone.",
"b02t03p18": "Great. That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final torso over it.",
"b02t03p19": "Take a look at Level 3 of the torso to fully understand how the muscles and plains work. Or why not share your drawing with us.",
"b02t04p01": "Start by laying out the lines that will represent the shoulders, elbows and hands.",
"b02t04p02": "Draw in a basic shape of the shoulders.",
"b02t04p03": "The limbs can be represented as cylinders for now.",
"b02t04p04": "Similar to the level 1 tutorial, draw a tapered cylinder for bottom half of the arm as it thins as it goes down towards the wrist.",
"b02t04p05": "That is the basic proportions mapped out. Lightly erase the lines and so we can bring the definition of the forms to the next level.",
"b02t04p06": "First, let us draw in the shoulder.",
"b02t04p07": "The main muscle of the arm comes out from below the lowest point of the deltoid. It stretches like this when the arm is flat",
"b02t04p08": "The triceps wrap around the back of the arm, framing the shoulder. We can only see a small part of them from this angle.",
"b02t04p09": "It is important to have a visual break in between where the lower half of the arm meets the top half.",
"b02t04p10": "I will outline the hand here, but it has its own separate tutorial in this book.",
"b02t04p11": "Great. That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final arm over it. Add in some extra details like the veins.",
"b02t04p12": "Take a look at level 3 of the arm to fully understand how the muscles and plains work. Or why not share your drawing with us.",
"b02t05p01": "Start by laying out the lines that will represent the hips, knees, limbs and feet.",
"b02t05p02": "The limbs can be represented as cylinders for now.",
"b02t05p03": "Similar to the level 1 tutorial, draw a tapered cylinder for bottom half of the leg as it thins as it goes down towards the foot.",
"b02t05p04": "That is the basic proportions mapped out. Lightly erase the lines and so we can bring the definition of the forms to the next level.",
"b02t05p05": "The groin and the glutes act similar to the shoulder in the arm. The limbs will emerge from here.",
"b02t05p06": "The top half of the leg is mainly built of three muscles. The bottom two reach down to the knees.",
"b02t05p07": "The knees are similar to the elbows, but its much larger and more prominent.",
"b02t05p08": "The calve muscles will form the large mass at the top of this part of the leg, it thins out as we drop towards the foot.",
"b02t05p09": "I will outline the foot here, but it has its own separate tutorial in this book.",
"b02t05p10": "Great. That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final legs over it.",
"b02t05p11": "Take a look at level 3 of the leg to fully understand how the muscles and plains work. Or why not share your drawing with us.",
"b02t06p01": "Start by drawing in some rectangles which will block out the shapes of the palms.",
"b02t06p02": "The fingers are broken up into three cylinders each.",
"b02t06p03": "Block them in, remembering that different size of each finger.",
"b02t06p04": "The bottom bone of the thumb is surrounded by a large area of flesh. So I draw it as a large cone rather than a cylinder.",
"b02t06p05": "The rest of the thumb is similar to the fingers.",
"b02t06p06": "That is the basic proportions mapped out. Lightly erase the lines and so we can bring the definition of the forms to the next level.",
"b02t06p07": "We can add in bumps for each knuckles.",
"b02t06p08": "That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final hand over it.",
"b02t06p09": "I like to draw the tips of the fingers a little thicker than the rest of the finger.",
"b02t06p10": "Take the definition up a level drawing in the fingernails, breaking up the sections of the finger, outlining the bones, and even adding in some veins.",
"b02t06p11": "Take a look at Level 3 of the hands to fully understand how the muscles and plains work. Or why not share your drawing with us.",
"b02t07p01": "The basic shape of the foot is a wedge. Make sure it has a flat face where the toes will extrude from.",
"b02t07p02": "It connects the leg with a cylinder, with the ankle bones on either side.",
"b02t07p03": "Draw in a large cylinder at the front of the wedge for the big toe.",
"b02t07p04": "The rest of the toes you can do as one block. Sculptors usually treat this area as one form.",
"b02t07p05": "Add in the fleshy area of the foot that is behind the toes. This is what creates the arch in your foot.",
"b02t07p06": "Then you can indicate the separate toes.",
"b02t07p07": "That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final foot over it.",
"b02t07p08": "Take the definition up a level drawing in the toenails.",
"b02t07p09": "Take a look at Level 3 of the feet to fully understand how the muscles and plains work. Or why not share your drawing with us.",
"b03t01p01": "We will start with the basic forms that we sketch in for the level 2 tutorial.",
"b03t01p02": "Take a look at the individual tutorials which looks in detail at each muscle.",
"b03t01p03": "From this angle, the sternocleidomastoid  and trapezius muscles slot right behind the clavicle.",
"b03t01p04": "The deltoid is attached to the biceps, pulling on it if the arm is raised. The triceps emerge out of the back of the deltoid.",
"b03t01p05": "The leg muscles come out from under the obliques and hip bone.",
"b03t01p06": "Outline the muscles on the foot.",
"b03t01p07": "And then the hand.",
"b03t01p08": "Great, let us take a look now and see what plains the anatomy can create. Look at it through the eyes of a sculptor.",
"b03t01p09": "Take a look at the individual tutorials which looks in detail at each section. The plains that the face makes really help define areas for adding in shading details.",
"b03t01p10": "Again the neck muscles appear to slot right into the area behind the collarbone.",
"b03t01p11": "The arms lock onto the shoulder.",
"b03t01p12": "As the legs emerge from the hip bone.",
"b03t01p13": "Remember to look at each individual tutorial.",
"b03t01p14": "Finish the full figure by drawing on the hands.",
"b03t02p01": "We will start with the basic forms that we sketched from the level 2 tutorial.",
"b03t02p02": "The frontalis muscle defines the forehead.",
"b03t02p03": "The orbital portion of the eye surrounds the eye lids.",
"b03t02p04": "The cheekbones are an important defining feature. The temporalis muscle acts as one of the side planes of the top half of the face.",
"b03t02p05": "The nasalis muscle is the bridge of the nose. The nose tip itself is broken into a few sections, one area for the centre point, the others to surround the nasal passages.",
"b03t02p06": "Smiling involves lots of muscles. The outer portion of the mouth has lots of muscles connected into it.",
"b03t02p07": "The mentalis muscle surrounded by the depressor labii inferioris creates a fleshy shape underneath and to the lower side of the mouth.",
"b03t02p08": "Lastly draw in the ear.",
"b03t02p09": "Great, now that we understand the muscles of the face a bit better, let us take a look at how they create plains on the face.",
"b03t02p10": "The forehead areas is one of the largest. Make sure to define the front and side planes of the face and follow those down throughout the head.",
"b03t02p11": "The brow creates a deep area for shadows. It cuts right back to behind the eye.",
"b03t02p12": "The bridge of the nose is a flat area, then the nose tips itself creates a few important planes, often casting a shadow beneath it.",
"b03t02p13": "A flat area runs from the nose down along the front plane of the face.",
"b03t02p14": "The cheeks create an strongly defined area as the plane goes down to the chin.",
"b03t02p15": "The side of the jaw can hollow under the line created by the cheekbones as it is a thin area which expands as the mouth opens.",
"b03t02p16": "The chin is a simple shape. The more defined it is often leads to the stereotypical heroic look.",
"b03t02p17": "The extrusion of the philtrum creates a groove that catches shade. You can break the top lip up to three areas.",
"b03t02p18": "As the chin meets the bottom lip, there is a round fleshy area which curves around to create the wrinkle that extends from the nose.",
"b03t02p19": "The ears have lots of hollows and extrusions. It takes a bit of practice to master.",
"b03t02p20": "Fantastic, that is it. With the knowledge of the muscle structure, and the planes they, along with the skull and skin create, you should be able to master drawing the head.",
"b03t03p01": "We will start with the basic forms that we sketched from the level 2 tutorial.",
"b03t03p02": "The pectoralis muscles connect to the bottom of the deltoids. It emerges from that one point across the body.",
"b03t03p03": "The ab muscles, or rectus abdominis go from below the chest down to the crotch.",
"b03t03p04": "The latissimus dorsi is the muscle which is runs around from the back and under the arm. The serratus anterior are the small muscles which connect them into the obliques.",
"b03t03p05": "The external obliques run up from the ab muscles into the serratus anterior.",
"b03t03p06": "The largest of the obliques goes around to the crotch area. This is largest area from the side of the torso.",
"b03t03p07": "The deltoids are strongly linked to the chest muscles.",
"b03t03p08": "The dominant neck muscles are the sternocleidomastoids which go from beneath the ear down towards the collarbone.",
"b03t03p09": "The trapezius wraps around behind the neck forming connecting the shoulder to the back of the head.",
"b03t03p10": "Great, now that we understand the muscles of the torso a bit better, let us take a look at how they create planes.",
"b03t03p11": "The chest and ribcage area are the most dominant muscles. They create large flat planes that cut in to create shadows underneath them.",
"b03t03p12": "The shoulders break into three sections from the deltoids. The middle one being the most dominant.",
"b03t03p13": "The abs cut into each other to create areas for shadows. The deltoids from here up to the lats.",
"b03t03p14": "From the underdrawing we can see how the rest of the muscles shape out the rest of the torso.",
"b03t03p15": "The adams apple extrudes out from the neck, and between it and the sternocleidomastoid is an intruded plane.",
"b03t03p16": "Fantastic, that is it. With the knowledge of the muscle structure, and the planes they, along with the bone and skin create, you should be able to master drawing the torso.",
"b03t04p01": "We will start with the basic forms that we sketched from the level 2 tutorial.",
"b03t04p02": "The deltoids run down into the same point between the top of the biceps and triceps.",
"b03t04p03": "The biceps are the dominant muscle and work in harmony with the triceps.",
"b03t04p04": "The triceps wrap around the elbow and split into two parts.",
"b03t04p05": "The brachioradialis go from alongside the biceps down to the wrist.",
"b03t04p06": "The flexor carpi radialis and the rest of the arm muscles rotate around and down to the wrist.",
"b03t04p07": "The flexor aponeurosis is almost like a wrist band wrapping around the lower part of the arm.",
"b03t04p08": "Great, now that we understand the muscles of the arm a bit better, let us take a look at how they create planes.",
"b03t04p09": "The more a person trains, the more defined their deltoids are.",
"b03t04p10": "The biceps can be cut into three main planes, which like the deltoid, creates a sharp edge as it comes to its end.",
"b03t04p11": "The triceps are extruded in a flat plane which curls around the back of the arm, the stronger the arm, the more the plane protrudes out.",
"b03t04p12": "The lower arm muscles curve around the arms. They knit into each other defining their separate areas.",
"b03t04p13": "Fantastic, that is it. With the knowledge of the muscle structure, and the planes they, along with the bone and skin create, you should be able to master drawing the arm.",
"b03t05p01": "We will start with the basic forms that we sketched from the level 2 tutorial.",
"b03t05p02": "The top half of the leg is comprised of three large muscles. The vastus medialis, the vastus lateralis and the rectus femoris.",
"b03t05p03": "The inside of the leg is divided from those muscles by the sartorius muscle which curves down around the inside of the leg.",
"b03t05p04": "The gluteus maximus and gluteus medius wrap around the back of the body and support the legs.",
"b03t05p05": "Draw in the knee bones.",
"b03t05p06": "The gastrocnemius muscles are the calve area of the leg.The tibialis anterior muscles are quite close to the tibia bone of the leg.",
"b03t05p07": "Just like the arms, the superior extensor retinaculum wraps like a band around the lower leg.",
"b03t05p08": "Great, now that we understand the muscles of the leg bit better, let us take a look at how they create planes on the face.",
"b03t05p09": "The three dominant leg muscles are the main planes of the leg.",
"b03t05p10": "Draw in the glutes.",
"b03t05p11": "The knee changes drastically as the leg bends. Treat it as two separate planes as the top protrudes out.",
"b03t05p12": "The calve muscles dominate the back of the leg. The tibia bone is the front point running down the leg.",
"b03t05p13": "Fantastic, that is it. With the knowledge of the muscle structure, and the planes they, along with the bone and skin create, you should be able to master drawing the legs.",
"b03t06p01": "We will start with the basic forms that we sketched from the level 2 tutorial.",
"b03t06p02": "The lumbricals run  long with the metacarpus bones from the exterior retinaculum down to the knuckles.",
"b03t06p03": "That is all the information we need for the hands.",
"b03t06p04": "The knuckles and the hand’s bones are the important shapes here.",
"b03t06p05": "Draw in the plane of the hand. The lower part of the thumb is one of the larger areas.",
"b03t06p06": "The fingers break into three individual parts. Look at the shape the fingertips can make, with the forward plane of each at an angle to make the tip the biggest part.",
"b03t06p07": "Each break in the finger has a knuckle, but the forward one is not as noticeable.",
"b03t07p01": "We will start with the basic forms that we sketched from the level 2 tutorial.",
"b03t07p02": "Similar to the hand, the lumbricals run along with the metatarsal bones from the superior exterior retinaculum down to the toe knuckles.",
"b03t07p03": "That is all the information we need for the feet.",
"b03t07p04": "The main area of the foot is like a wedge. Note the flat area on the top and how the mass creates the arch underneath the foot.",
"b03t07p05": "The back of the boot squashes down onto the ground.",
"b03t07p06": "Treat the tips of the toes similarly to the tips of the fingers.",
"b03t07p07": "Then the rest of the toes act as arched cylinders connecting the toes to the foot.",
"b04t01p01": "Let’s bend the arm up like a bicep curl to show the muscle contracting.",
"b04t01p02": "Build up the drawing like you would always, starting with the simple forms.",
"b04t01p03": "Use these forms as basic guidelines.",
"b04t01p04": "Rough out the basic shapes of the muscles",
"b04t01p05": "",
"b04t01p06": "",
"b04t01p07": "",
"b04t01p08": "Now let us erase these lines and draw in the muscles to examine how they work together",
"b04t01p09": "The chest muscles all originate at a point towards the deltoid and biceps muscles.",
"b04t01p10": "They work in harmony together.",
"b04t01p11": "",
"b04t01p12": "As the biceps contracts, pulling up the forearm, it grows in size.",
"b04t01p13": "",
"b04t01p14": "The triceps relaxes as the biceps contracts.",
"b04t01p15": "",
"b04t01p16": "",
"b04t01p17": "The forearm will bulge as it compresses against the upper arm.",
"b04t01p18": "",
"b04t01p19": "Lightly erase the construction lines and draw over them.",
"b04t01p20": "The biceps is often the defining muscle of the arm.",
"b04t02p01": "Let’s rotate the wrist to watch how the lower arm muscles can pop.",
"b04t02p02": "Build up the drawing like you would always, starting with the simple forms.",
"b04t02p03": "Use these forms as basic guidelines.",
"b04t02p04": "Rough out the basic shapes of the muscles.",
"b04t02p05": "",
"b04t02p06": "The forearm muscles mostly wrap around the arm.",
"b04t02p07": "Now let us erase these lines and draw in the muscles to examine how they work together.",
"b04t02p08": "",
"b04t02p09": "",
"b04t02p10": "",
"b04t02p11": "",
"b04t02p12": "",
"b04t02p13": "The brachioradialis muscle contracts and bulges out.",
"b04t02p14": "Most of the forearm muscles follow it around.",
"b04t02p15": "But some, closer in line with the elbow will still run straight down to the wrist.",
"b04t02p16": "",
"b04t02p17": " Lightly erase the construction lines and draw over them.",
"b04t02p18": "The forearm muscles will pop the more you rotate the wrist.",
"b04t03p01": "Let us rotate the arm to watch how the tricep muscles can pop.",
"b04t03p02": "Build up the drawing like you would always, starting with the simple forms.",
"b04t03p03": "Use these forms as basic guidelines.",
"b04t03p04": "Rough out the basic shapes of the muscles.",
"b04t03p05": "",
"b04t03p06": "",
"b04t03p07": "",
"b04t03p08": "",
"b04t03p09": "",
"b04t03p10": "The biceps is relaxed and flat in this pose.",
"b04t03p11": "The triceps will bulge as they contract.",
"b04t03p12": "",
"b04t03p13": "",
"b04t03p14": "",
"b04t03p15": "",
"b04t03p16": "",
"b04t03p17": "",
"b04t03p18": "Lightly erase the construction lines and draw over them.",
"b04t03p19": "The defined triceps can cast a shadow as it cuts in to meet the elbow.",
"b04t04p01": "Let us draw the arm as it naturally falls.",
"b04t04p02": "Build up the drawing like you would always, starting with the simple forms.",
"b04t04p03": "Use these forms as basic guidelines.",
"b04t04p04": "Rough out the basic shapes of the muscles.",
"b04t04p05": "",
"b04t04p06": "",
"b04t04p07": "",
"b04t04p08": "",
"b04t04p09": "",
"b04t04p10": "",
"b04t04p11": "",
"b04t04p12": "",
"b04t04p13": "",
"b04t04p14": "",
"b04t04p15": "",
"b04t04p16": "",
"b04t05p01": "Let us look at the deltoid muscles as they raise up the arm.",
"b04t05p02": "Build up the drawing like you would always, starting with the simple forms.",
"b04t05p03": "Use these forms as basic guidelines.",
"b04t05p04": "Rough out the basic shapes of the muscles.",
"b04t05p05": "",
"b04t05p06": "",
"b04t05p07": "",
"b04t05p08": "The deltoid wraps around the trapezius.",
"b04t05p09": "",
"b04t05p10": "The biceps contact the pull the forearm up.",
"b04t05p11": "The triceps relaxes, alternating with the biceps.",
"b04t05p12": "",
"b04t05p13": "",
"b04t05p14": "",
"b04t05p15": "",
"b04t05p16": "",
"b04t05p17": "",
"b04t05p18": "",
"b04t06p01": "Let us look at the deltoid muscles as they raise up the arm.",
"b04t06p02": "Build up the drawing like you would always, starting with the simple forms.",
"b04t06p03": "Use these forms as basic guidelines.",
"b04t06p04": "Rough out the basic shapes of the muscles.",
"b04t06p05": "",
"b04t06p06": "",
"b04t06p07": "Lots of squashing of muscle and contracting here.",
"b04t06p08": "",
"b04t06p09": "",
"b04t06p10": "",
"b04t06p11": "The biceps are contracted here, but they are also pushed forward by the arm and chest.",
"b04t06p12": "The triceps relax letting the arm bend.",
"b04t06p13": "",
"b04t06p14": "The brachioradialis muscle contracts and bulges out. It is also soft so it can be pushed out by other parts of anatomy.",
"b04t06p15": "",
"b04t06p16": "",
"b04t06p17": "",
"b04t06p18": "",
"b04t06p19": "",
"b04t07p01": "Let us draw the arm as it naturally falls.",
"b04t07p02": "Build up the drawing like you would always, starting with the simple forms.",
"b04t07p03": "Use these forms as basic guidelines.",
"b04t07p04": "Rough out the basic shapes of the muscles.",
"b04t07p05": "",
"b04t07p06": "",
"b04t07p07": "",
"b04t07p08": "",
"b04t07p09": "",
"b04t07p10": "",
"b04t07p11": "",
"b04t07p12": "",
"b04t07p13": "",
"b04t07p14": "",
"b04t07p15": "",
"b05t01p01": "Let us study the body as it is in motion.",
"b05t01p02": "Every image here is referenced with a UFC fighter filmed with a HD high speed camera.",
"b05t01p03": "When the figure is in motion, the line between the hips will alternate with the line between the shoulders.",
"b05t01p04": "As always, build up the forms over the simple skeletal structure.",
"b05t01p05": "Reference the accompanying video to see the figure in motion.",
"b05t01p06": "",
"b05t01p07": "As the cylinders we use for the legs and arms point away or towards us, the 3D volume of the shape can be seen.",
"b05t01p08": "",
"b05t01p09": "",
"b05t01p10": "",
"b05t01p11": "Lightly erase these lines so we can draw in the muscles in more detail.",
"b05t01p12": "Use the individual tutorials to help with the forms of each part of the body.",
"b05t01p13": "As the torso twists we can see the forms of the latissimus dorsi and the external oblique down the side of the figure.",
"b05t01p14": "The arms alternate with the legs for balance.",
"b05t01p15": "",
"b05t01p16": "The right foot is firmly planted on the ground as it is about to take off.",
"b05t01p17": "Great. That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final figure over it.",
"b05t02p01": "As the head turns, we can clearly see the front and side planes of the face.",
"b05t02p02": "The shoulders and hips still alternate as the figure springs up while twisting.",
"b05t02p03": "As always, build up the forms over the simple skeletal structure.",
"b05t02p04": "The torso elongates as the figure stretches up.",
"b05t02p05": "The glutes are twisted around in a much different direction than the chest.",
"b05t02p06": "The right leg is extended to thrust the body into the air.",
"b05t02p07": "",
"b05t02p08": "The forearm of the left arm is pointed right at us.",
"b05t02p09": "As is the left hand.",
"b05t02p10": "",
"b05t02p11": "Lightly erase these lines so we can draw in the muscles in more detail.",
"b05t02p12": "Use the individual tutorials to help with the forms of each part of the body.",
"b05t02p13": "The oblique muscle turns around the side of the body from the abs up to the lats.",
"b05t02p14": "",
"b05t02p15": "",
"b05t02p16": "",
"b05t02p17": "Great. That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final figure over it.",
"b05t03p01": "The figure, now mid air is about to explode into a high kick.",
"b05t03p02": "The arms are balancing the figure out.",
"b05t03p03": "As always, build up the forms over the simple skeletal structure.",
"b05t03p04": "",
"b05t03p05": "",
"b05t03p06": "Even when the part of the body is obscured, you should still draw the form in.",
"b05t03p07": "",
"b05t03p08": "Remember each section of the figure is outlined in detail in the figure books.",
"b05t03p09": "",
"b05t03p10": "Lightly erase these lines so we can draw in the muscles in more detail.",
"b05t03p11": "",
"b05t03p12": "Look at how the chest muscles raise as the shoulders are raised up.",
"b05t03p13": "",
"b05t03p14": "",
"b05t03p15": "",
"b05t03p16": "Great. That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final figure over it.",
"b05t04p01": "The shoulders and hips alternate as the figure is about to kick.",
"b05t04p02": "As always, build up the forms over the simple skeletal structure.",
"b05t04p03": "With the arms raised, the lats are visible to the side of the figure.",
"b05t04p04": "",
"b05t04p05": "Reference the accompanying video to see the figure in motion.",
"b05t04p06": "",
"b05t04p07": "",
"b05t04p08": "",
"b05t04p09": "Even when the part of the body is obscured, you should still draw the form in.",
"b05t04p10": "",
"b05t04p11": "Lightly erase these lines so we can draw in the muscles in more detail.",
"b05t04p12": "",
"b05t04p13": "As the torso is contracted on the figures right side, so the obliques are closer together.",
"b05t04p14": "The right bicep flattens out as it relaxes.",
"b05t04p15": "",
"b05t04p16": "",
"b05t04p17": "Great. That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final figure over it.",
"b05t05p01": "This will be the point of impact for the kick.",
"b05t05p02": "The right leg fully extends as it kicks out.",
"b05t05p03": "The hips and the shoulders have rotated in opposite directions to give the kick an extra force.",
"b05t05p04": "As always, build up the forms over the simple skeletal structure.",
"b05t05p05": "",
"b05t05p06": "",
"b05t05p07": "Even when the part of the body is obscured, you should still draw the form in.",
"b05t05p08": "",
"b05t05p09": "Lightly erase these lines so we can draw in the muscles in more detail.",
"b05t05p10": "",
"b05t05p11": "The torso is twisted and contracted as the hips swing around.",
"b05t05p12": "",
"b05t05p13": "",
"b05t05p14": "",
"b05t05p15": "Great. That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final figure over it.",
"b05t06p01": "The foot will now swing around in front of the figure.",
"b05t06p02": "The shoulders and hips are still alternated, an important gesture to show motion.",
"b05t06p03": "As always, build up the forms over the simple skeletal structure.",
"b05t06p04": "",
"b05t06p05": "",
"b05t06p06": "The foot is pointed right at us so we can see the glutes underneath it.",
"b05t06p07": "",
"b05t06p08": "",
"b05t06p09": "The lower part of the leg is pointed directly at us.",
"b05t06p10": "",
"b05t06p11": "Lightly erase these lines so we can draw in the muscles in more detail.",
"b05t06p12": "With the arm raised we get a good view of the serratus anterior muscles.",
"b05t06p13": "",
"b05t06p14": " Remember each section of the figure is outline in detail in the figure books.",
"b05t06p15": "",
"b05t06p16": "",
"b05t06p17": "Great. That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final figure over it.",
"b05t07p01": "The figure begins to land.",
"b05t07p02": "The shoulders and hips are still alternated.",
"b05t07p03": "As always, build up the forms over the simple skeletal structure.",
"b05t07p04": "",
"b05t07p05": "",
"b05t07p06": "The right leg now crosses completely over the front of the body.",
"b05t07p07": "The top part of the left arm is pointed directly at us.",
"b05t07p08": "",
"b05t07p09": "",
"b05t07p10": "",
"b05t07p11": "Lightly erase these lines so we can draw in the muscles in more detail.",
"b05t07p12": "",
"b05t07p13": "The torso begins to relax.",
"b05t07p14": "",
"b05t07p15": "Remember each section of the figure is outlined in detail in the figure books.",
"b05t07p16": "",
"b05t07p17": "Great. That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final figure over it.",
"b05t08p01": "The figure fully lands on the ground.",
"b05t08p02": "The shoulders and torso begin to rest level with each other.",
"b05t08p03": "As always, build up the forms over the simple skeletal structure.",
"b05t08p04": "",
"b05t08p05": "",
"b05t08p06": "Reference the accompanying video to see the figure in motion.",
"b05t08p07": "",
"b05t08p08": "The right leg is still crossed over as it comes to rest.",
"b05t08p09": "The arm can relax as it is not needed for balance.",
"b05t08p10": "",
"b05t08p11": "Lightly erase these lines so we can draw in the muscles in more detail.",
"b05t08p12": "",
"b05t08p13": "We still have a twist between the chest and the waist.",
"b05t08p14": "",
"b05t08p15": "Remember each section of the figure is outlined in detail in the figure books.",
"b05t08p16": "",
"b05t08p17": "Great. That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final figure over it.",
"b06t01p01": "Start by laying down the basic shape of the head",
"b06t01p02": "Using the size of the head, we can lay out markers for proportions",
"b06t01p03": "Your hero is 8 heads high",
"b06t01p04": "Lay out the figure as simply as this. With circles as the joints and lines to indicate the limbs and torso",
"b06t01p05": "Note the shoulders should be half a head down",
"b06t01p06": "The Hands reach down at the bottom of the 4th head alongside the hips",
"b06t01p07": "The legs reach down to 8 heads down. With these indicators, we can lay more solid down forms on top",
"b06t01p08": "Two three dimensional shapes, the Top and bottom forms are cylinders, and the middle one is a sphere",
"b06t01p09": "Draw in the larger top cylinder to represent the chest",
"b06t01p10": "A sphere for the stomach, which can help us visualise how the torso can bend and rotate if we were twisting the body",
"b06t01p11": "And the small cylinder for the waist",
"b06t01p12": "These spheres will represent the ball and socket joints that our arms and legs rotate from. Namely the shoulder and the hips",
"b06t01p13": "Some more three dimensional shapes we will use for the arms and the legs",
"b06t01p14": "Start off the arms and legs with a long cylinder that reaches the ball we drew to mark the elbow",
"b06t01p15": "Then use a tapered cylinder for the lower half of each limb",
"b06t01p16": "The hands are covered in more detail in their own tutorial. Draw in the shapes for the legs, and connect the forms together",
"b06t01p17": "Finally, draw in a cylinder to represent the neck",
"b06t01p18": "Using the head tutorial, draw in where the facial features will go",
"b06t01p19": "The chest line will go from the point where your arm meets the Shoulder, down to the line that is two heads down",
"b06t01p20": "I like to connect the major cylinders together",
"b06t01p21": "Great. That’s the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final figure over it.",
"b06t01p22": "Use the head tutorial and draw in what is often the most important part of your figure",
"b06t01p23": "Draw in the neck and whatever neckline you want depending on what clothes your figure is wearing",
"b06t01p24": "Now outline the shoulder and arms. Note the trapezius muscle will make the line from his shoulder go up around his neck",
"b06t01p25": "Most tops will go down the belt line, which is at the top of your cylinder",
"b06t01p26": "Then outline those chest muscles",
"b06t01p27": "Use a lot of straight lines to draw in the legs. Most important is to outline the difference in shapes between the thighs and the calves",
"b06t01p28": "Keep the foot nice and simple",
"b06t01p29": "And there you have it.  You can fully erase the basic forms now to show off your character",
"b06t02p01": "Let’s start with an oval shape to represent the head",
"b06t02p02": "Draw two lines across to split it up into thirds",
"b06t02p03": "Our face will look straight ahead, so draw a line down the middle to represent the middle of the face.",
"b06t02p04": "Let’s take a look at this form represented by a 3D shape. This should help you visualise how the centre line rotates around the form as we look at it from a different angle",
"b06t02p05": "Now, to help us lay out where the features go, let us add some more lines. Take the middle and bottom segment, and draw a line 1/3rd down in each segment",
"b06t02p06": "We now know where to put the facial features. Let us add in ovals for the eyes along this line",
"b06t02p07": "Draw a line from the centre of the eyes straight down the head. This will tell us exactly where to draw the mouth",
"b06t02p08": "The top line is where we draw the eyebrows. You can draw the basics shapes of a rectangle joined to a triangle",
"b06t02p09": "Where the centre line meets our third line, is where to put the nose. Remember, check the facial features book that outlines how to draw the nose",
"b06t02p10": "The the mouth goes on the bottom line, and its width goes from the two centre lines drawn from our eyes",
"b06t02p11": "We know where to put the ear thanks to the lines from our nose and eyes",
"b06t02p12": "Let’s sharpen up the jaw line. Bring it to meet the chin, which is directly under the mouth, using the same lines from the eye",
"b06t02p13": "Add in the hair line",
"b06t02p14": "Great. That’s the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final figure over it",
"b06t02p15": "Remember, the facial features are important, and we have a whole book dedicated to them.  Use it to learn how to draw them from each angle",
"b06t02p16": "Everybodys features are different. Feel free to experiment with different facial shapes and sizes.",
"b06t02p17": "Use the forms we laid out as guides where to draw in the detailed versions of each feature",
"b06t02p18": "We look at the ear in the features book too",
"b06t02p19": "Now draw in the crown of the head, or use the outline to draw whatever hairstyle you like",
"b06t02p20": "Draw in the jaw line, ignoring the curve of the initial oval",
"b06t02p21": "Now the hairline.",
"b06t02p22": "Add in a few features. A line from the chin up towards the ear can indicate a strong jawline",
"b06t02p23": "I like to indicate the bottom lip with a small line which helps tell us that the lip protrudes from the face.",
"b06t02p24": "A small curve can show the “ala” area around the nostril",
"b06t02p25": "And a curve here can help define the planes of the face.",
"b06t02p26": "And there you have it.  You can fully erase the basic forms now",
"b06t02p27": "Take a look at Level 2 of this figure to take your drawing up to the next stage. Or why not share your drawing with us.",
"b06t03p01": "Drawing the hands at an angle can be difficult. So always take a look at your own hands for reference. Draw in two rectangles as the palms of your hand ",
"b06t03p02": " Break the finger joints down into rectangles that extend from the top of your palm of your hand",
"b06t03p03": " The tops of these rectangles curve down to indicate middle finger being the longest and the pinky being the smallest",
"b06t03p04": "Your fingers have three joints and there for three bendable areas.  ",
"b06t03p05": "Extending from the palm, I like to draw a cylinder, almost representing the first bone of your thumb as a ball joint ",
"b06t03p06": "The second bone of the thumb extends from this like the fingers ",
"b06t03p07": "And the third follows.",
"b06t03p08": "Break the rectangles used to outline the fingers into their own parts",
"b06t03p09": "Separate them out.",
"b06t03p10": "",
"b06t03p11": "Great. That’s the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final hand over it",
"b06t03p12": "Each finger joins your sectioned off rectangles together.",
"b06t03p13": "Remember, the middle finger is the longest",
"b06t03p14": "The ring finger is slightly longer than the index finger",
"b06t03p15": "The pinky is the smallest",
"b06t03p16": "Let's draw the thumb, but note, we only indicate a small part of the ball joint, as the flesh surrounding it blends into the hand",
"b06t03p17": "We can outline the hands going into the palms using the rectangle we drew in stage one",
"b06t03p18": "Draw in the extra details like the fingernails.",
"b06t03p19": "And there you have it.  You can fully erase the basic forms now",
"b06t03p20": "Take a look at Level 2 of the hand to take your drawing up to the next stage. Or why not share your drawing with us",
"b07t01p01": "Start by laying down the basic shape of the head.",
"b07t01p02": "Using the size of the head, we can lay out markers for proportions. .Our figure is 8 heads high.",
"b07t01p03": "Lay out the figure as simply as this. With circles as the joints and lines to indicate the limbs and torso. Use the level 1 tutorial if you need help here.",
"b07t01p04": "Now we can draw in the basic forms starting with the chest.",
"b07t01p05": "Remember, each section is individually covered in more detail in this book.",
"B07t01p06": "Always reference the grid of 8 heads to know where to line up the features. The belly button should be 3 heads down.",
"b07t01p07": "The hips should be around 4 heads down.",
"b07t01p08": "At this stage, the legs and the arms can be treated similarly.",
"b07t01p09": "The bottom half of the leg and hand get thinner as they reach towards the wrist and foot.",
"b07t01p10": "Use the tutorials for the hand and the foot when you are drawing them in.",
"b07t01p11": "Outline the hands and the feet. Reference their individual tutorials.",
"b07t01p12": "Lastly connect the head to the neck.",
"b07t01p13": "That is the basic proportions mapped out. Lightly erase the lines and let us take the definition of the forms to the next level.",
"b07t01p14": "Here is where the individual tutorials really come into play. Make sure you look at them.",
"b07t01p15": "Continue refining the forms.",
"b07t01p16": "Look at how the body parts interconnect. The chest muscle connects strongly to the shoulder, which the arm muscle emerges from.",
"b07t01p17": "Similarly, the legs emerge from the hips.",
"b07t01p18": "Draw in the feet.",
"b07t01p19": "And the hands, referring the their tutorials.",
"b07t01p20": "Great. That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final figure over it",
"b07t01p21": "Take a look at Level 3 of the full figure to fully understand how the muscles and plains work. Or why not share your drawing with us.",
"b07t02p01": "Start with a simple spherical shape for the head.",
"b07t02p02": "Take a look at this form represented by a 3D shape. This should help you visualise how the centre line rotates around the form as we look at it from a different angle.",
"b07t02p03": "Draw in a horizontal and vertical line through the sphere. With the vertical one at an angle in the direction that the head will look towards.",
"b07t02p04": "The head is not fully round, in fact it is important to create the planes of the face that are the side of the head and the front of the face.",
"b07t02p05": "We can create those planes by taking a vertical slice off the sphere.",
"b07t02p06": " From these four points we can draw in the bottom half of the face.",
"b07t02p07": "Take the point where the jaw line meets the chopped sphere as a halfway marker from the spheres midline, in order to find out how far down the chin should go.",
"b07t02p08": "Now we can clearly see the planes of the face.  ",
"b07t02p09": "Lightly erase some lines to give us a better view.",
"b07t02p10": "Now draw a line horizontally half ways down our skull shape. This will be the eye line. Divide the front plane in half too.",
"b07t02p11": " Draw some more horizontal lines down. One that is 1/3rd down from the eyes to the jaw. The other just slightly lower, marked by the bottom of our original sphere.",
"b07t02p12": "Now, like in the level 1 tutorial, we can mark in where the facial features go.",
"b07t02p13": "Draw a line from the centre of the eyes down to mark out where the chin and mouth should go.",
"b07t02p14": "Remember, the facial features are covered in depth in their own book.",
"b07t02p15": "The ear should go from the bottom of the nose, up to the eyebrows.",
"b07t02p16": "Draw in your characters hairline, which can help define the planes of the face.",
"b07t02p17": "Great. That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final head over it.",
"b07t02p18": "I like to start with the eyes as they are often the first feature we look at.",
"b07t02p19": "Add in the nose.",
"b07t02p20": "The eyebrows.",
"b07t02p21": "The mouth.",
"b07t02p22": "And the ears.",
"b07t02p23": "We can use our layout lines to draw the shape of the face. Depending on the face you are drawing, you can add in a slight protrusion for the cheek bones.",
"b07t02p24": "Follow the lines around and mark in the hairline to complete the basic head shape.",
"b07t02p25": "And there you have it.  You can fully erase the basic forms now.",
"b07t02p26": "Take a look at Level 3 of the head to fully understand how the muscles and plains work. Or why not share your drawing with us.",
"b07t03p01": "Start by laying out the lines that will represent the shoulders, and hips.",
"b07t03p02": "The chest should stretch from shoulder to shoulder.",
"b07t03p03": "The rib cage and the back is a large form that takes up most of the volume of the torso.",
"b07t03p04": "The bottom half of the torso is shaped like a cylinder, down to the waist.",
"b07t03p05": "The shoulders connect into the chest. They rise up higher following there the collarbone will go",
"b07t03p06": "The neck then emerges from the chest, it will connected to the face by a group of muscles.",
"b07t03p07": "The area that will be the abs comes down from the ribcage. It goes right down passed the waist towards the groin area.",
"b07t03p08": "That is the basic proportions mapped out. Lightly erase the lines and so we can bring the definition of the orms to the next level.",
"b07t03p09": "The pecs are two separate large muscles.",
"b07t03p10": "Define the collarbone as it goes from the top of the chest over the shoulder.",
"b07t03p11": "The shoulders will connect to the arms through the deltoid.",
"b07t03p12": "Draw in the ribcage at the front and then the lats which wrap around from under the shoulder to the back.",
"b07t03p13": "Now the abs. Note how one the belly button is in a gap between four abs.",
"b07t03p14": "The oblique muscles emerge from the side of the abs at an angle up towards the lats.",
"b07t03p15": "Draw in four small muscles which will connect the lats to the obliques.",
"b07t03p16": "Then define the hips.",
"b07t03p17": "Finally, the neck muscles. The most important two at the front, connect from the ears, down to the middle point of the collarbone.",
"b07t03p18": "Great. That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final torso over it.",
"b07t03p19": "Take a look at Level 3 of the torso to fully understand how the muscles and plains work. Or why not share your drawing with us.",
"b07t04p01": "Start by laying out the lines that will represent the shoulders, elbows and hands.",
"b07t04p02": "Draw in a basic shape of the shoulders.",
"b07t04p03": "The limbs can be represented as cylinders for now.",
"b07t04p04": "Similar to the level 1 tutorial, draw a tapered cylinder for bottom half of the arm as it thins as it goes down towards the wrist.",
"b07t04p05": "That is the basic proportions mapped out. Lightly erase the lines and so we can bring the definition of the forms to the next level.",
"b07t04p06": "First, let us draw in the shoulder.",
"b07t04p07": "The main muscle of the arm comes out from below the lowest point of the deltoid. It stretches like this when the arm is flat",
"b07t04p08": "The triceps wrap around the back of the arm, framing the shoulder. We can only see a small part of them from this angle.",
"b07t04p09": "It is important to have a visual break in between where the lower half of the arm meets the top half.",
"b07t04p10": "I will outline the hand here, but it has its own separate tutorial in this book.",
"b07t04p11": "Great. That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final arm over it. Add in some extra details like the veins.",
"b07t04p12": "Take a look at level 3 of the arm to fully understand how the muscles and plains work. Or why not share your drawing with us.",
"b07t05p01": "Start by laying out the lines that will represent the hips, knees, limbs and feet.",
"b07t05p02": "The limbs can be represented as cylinders for now.",
"b07t05p03": "Similar to the level 1 tutorial, draw a tapered cylinder for bottom half of the leg as it thins as it goes down towards the foot.",
"b07t05p04": "That is the basic proportions mapped out. Lightly erase the lines and so we can bring the definition of the forms to the next level.",
"b07t05p05": "The groin and the glutes act similar to the shoulder in the arm. The limbs will emerge from here.",
"b07t05p06": "The top half of the leg is mainly built of three muscles. The bottom two reach down to the knees.",
"b07t05p07": "The knees are similar to the elbows, but its much larger and more prominent.",
"b07t05p08": "The calve muscles will form the large mass at the top of this part of the leg, it thins out as we drop towards the foot.",
"b07t05p09": "I will outline the foot here, but it has its own separate tutorial in this book.",
"b07t05p10": "Great. That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final legs over it.",
"b07t05p11": "Take a look at level 3 of the leg to fully understand how the muscles and plains work. Or why not share your drawing with us.",
"b07t06p01": "Start by drawing in a rectangle which will block out the shape of the palm.",
"b07t06p02": "The fingers are broken up into three cylinders each.",
"b07t06p03": "Block them in, remembering that different size of each finger.",
"b07t06p04": "The bottom bone of the thumb is surrounded by a large area of flesh. So I draw it as a large cone rather than a cylinder.",
"b07t06p05": "The rest of the thumb is similar to the fingers.",
"b07t06p06": "That is the basic proportions mapped out. Lightly erase the lines and so we can bring the definition of the forms to the next level.",
"b07t06p07": "We can add in bumps for each knuckles.",
"b07t06p08": "That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final hand over it.",
"b07t06p09": "I like to draw the tips of the fingers a little thicker than the rest of the finger.",
"b07t06p10": "Take the definition up a level drawing in the fingernails, breaking up the sections of the finger, outlining the bones, and even adding in some veins.",
"b07t06p11": "Take a look at Level 3 of the hands to fully understand how the muscles and plains work. Or why not share your drawing with us.",
"b07t07p01": "The basic shape of the foot is a wedge. Make sure it has a flat face where the toes will extrude from.",
"b07t07p02": "It connects the leg with a cylinder, with the ankle bones on either side.",
"b07t07p03": "Draw in a large cylinder at the front of the wedge for the big toe.",
"b07t07p04": "The rest of the toes you can do as one block. Sculptors usually treat this area as one form.",
"b07t07p05": "Add in the fleshy area of the foot that is behind the toes. This is what creates the arch in your foot.",
"b07t07p06": "Then you can indicate the separate toes.",
"b07t07p07": "That is the hard work done, you have laid out the important forms. Go ahead and lightly erase those lines to draw your final foot over it.",
"b07t07p08": "Take the definition up a level drawing in the toenails.",
"b07t07p09": "Take a look at Level 3 of the feet to fully understand how the muscles and plains work. Or why not share your drawing with us."

]




